-- Make clangd play nice with PlatformIO / ESP32 GCC toolchains.
--
-- clangd reads compile_commands.json (generated by `pio run -t compiledb`)
-- for the project's own include paths, but it will NOT trust the embedded
-- GCC toolchain's *built-in* headers (stdint.h, <cstdint>, etc.) unless we
-- explicitly allow it to query that compiler. Without --query-driver you get
-- "unknown type name 'uint8_t'" even when Arduino.h resolves fine.
return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      clangd = {
        cmd = {
          "clangd",
          "--background-index",
          "--clang-tidy",
          -- Header auto-insertion: with "iwyu" (include-what-you-use), clangd
          -- auto-adds the granular header for each symbol you autocomplete
          -- (e.g. HardwareSerial.h for `Serial`, esp32-hal-gpio.h for
          -- `pinMode`). In Arduino/ESP32 code that's redundant noise, since
          -- `#include <Arduino.h>` is the umbrella header that already pulls
          -- them all in. "never" disables it so we manage includes ourselves.
          "--header-insertion=never",
          "--completion-style=detailed",
          "--function-arg-placeholders",
          "--fallback-style=llvm",
          -- Allow clangd to invoke the ESP32 GCC drivers to discover their
          -- built-in system include paths. Covers both RISC-V (C3/C6/H2)
          -- and Xtensa (classic ESP32/S2/S3) toolchains.
          -- clangd does its own globbing here, so pass the pattern literally
          -- (only expand ~). Matches *-elf-gcc and *-elf-g++.
          "--query-driver=" .. vim.fn.expand("~") .. "/.platformio/packages/**/bin/*-elf-g*",
        },
      },
    },
  },
}
